### ISSUE TITLE
ecarey-r7/editor does not exist

### ISSUE THREAD

**Issue by ctennis** [erran-r7/metasploit-cookbook#1]
Berksfile references it, which causes errors on building the vagrant environment.

**Comment by erran** [comment]
@ctennis yeah, the cookbooks references are scattered between my Rapid7 GitHub and rapid7-cookbooks. The only cookbooks I'm actively supporting are the vulnerable app ones for now. I'll update this cookbook during the week. It's cool to see someone actually noticed one of the cookbook repositories so early though.

Note that none of the content under Rapid7-cookbooks is official yet. There will probably be a blog post by @todb-r7 when it is.

Leave this issue open since it obviously needs to be addressed before official support happens.

**Comment by erran** [comment]
My -r7 account: (@ecarey-r7)

**Comment by erran** [comment]
Also know that the ones under my r7 account aren't complete yet either.

**Comment by johntdyer** [comment]
@ipwnstuff  Any idea when that cookbook will be published?  This is sort of a blocker for anyone trying to play around w/ this Vagrant project...

**Comment by erran** [comment]
Yeah, it's a definite blocker... Sorry about that, if you read this thread and guessed by the lack of activity there isn't much need for this cookbook/vagrant project yet. Currently at rapid7 this cookbook isn't being used (it was never even technically completed), so I'll have to take personal time to help maintain it.

I can take some time later to fix this issue, **but** these cookbooks (under the organization) aren't yet being used actively by anyone (they were written by me while I was interning. My new job doesn't give me as much time to use Chef/Vagrant, though in the long run I'll become more active with Chef/Vagrant.

With the exception of a few coworkers recently starting to write chef cookbooks publicly) Che. Read through the development environment setup on metasploit's GitHub wiki to see what this cookbook and the referenced cookbooks were meant to accomplish.

**Comment by erran** [comment]
> Note that none of the content under Rapid7-cookbooks is official yet. There will probably be a blog post by todb-r7 when it is.

This still applies, these cookbooks are a long way from being useable, but they're open source, so they can be improved by contributors like you guys.

**Comment by johntdyer** [comment]
ok, but I have no clue what "editor" is, so I am not sure what functionality I need to replace to make this work

**Comment by johntdyer** [comment]
Is there a reason you can't publish editor, even if it's not "ready" ?

**Comment by erran** [comment]
It could be as simply as `package "vim"`. There are some recommended plugins on the wiki. I think editor is under @ecarey-r7 , so you may be able to update the link to it in the Berksfike.

**Comment by erran** [comment]
Actually, that repo is empty. It should be possible to just use this recipe/cookbook: https://github.com/ecarey-r7/gvim-cookbook/blob/master/recipes/default.rb

**Comment by johntdyer** [comment]
While vim is great I think maybe the better option is to remove the dependency since its not required for metasploit

**Comment by erran** [comment]
This cookbook was intended to be used for setting up the metasploit development environment in which Vim is the easiest to install recommended editor.

**Comment by johntdyer** [comment]
Yes, but if you guys want this to be a community thing then making users 
opt-in rather then opt-out of dependencies might be a better approach

Erran Carey wrote:

**Comment by erran** [comment]
Yeah, that's why I created the editor cookbook to abstract the deps. Like I mentioned before this project hasn't been touched, nor thought of. It'd probably be better off if I removed and rewrote it from scratch. I'll do exactly that when I get a chance too. If you want to use this for now go ahead, **BUT** it's not supported by Rapid7 (I should move the unsupported repositories to ecarey-r7 for now).
